### ISSUE TITLE
As a player in-game, I want information about the current round's youtube video to be revealed incrementally to try and deduce if the comments in my hand match the video

### ISSUE THREAD

**Issue by RoVi80** [sopra-fs23-group-08/server#12]
Story: As a player in-game, I would like to see all the currently revealed information about the YouTube video to try and deduce whether my hand (comments) might match the video 

Acceptance criteria: 

- [ ] sopra-fs23-group-08/client#17
- [x] sopra-fs23-group-08/client#16
- [ ] sopra-fs23-group-08/client#15

Priority: Critical 
Estimate: 4-8h

**Comment by S3r4f1n** [comment]
Client receives information incrementally: 937317224af2009d37736890c155ed60dcb2fcf8
