### ISSUE TITLE
As a player during my turn, I want to be able to call/raise/fold to participate in the game

### ISSUE THREAD

**Issue by RoVi80** [sopra-fs23-group-08/server#13]
Story : As a player during my turn, I want to decide whether I raise, call, fold to progress the current round 

Acceptance criteria: 

- [x] sopra-fs23-group-08/client#18
- [x] sopra-fs23-group-08/server#44
- [x] sopra-fs23-group-08/server#45
- [x] sopra-fs23-group-08/server#47
- [x] sopra-fs23-group-08/server#48

Priority: Critical 
Estimate: 12 h

**Comment by S3r4f1n** [comment]
FE in Commit: 81167ed4d574767f58f8eb17b76a31310b4b8019 (Game2.js)
BE in Commit: 236f74a333977cc6dc0c5824c7535abde7b33244
BE in Commit: f333b9eecb9b409b9e1a2fac8294bfa6bd31cd99
