### ISSUE TITLE
As a player in-game I want to see other players current score, bet and last turn-decision to inform my game-decisions

### ISSUE THREAD

**Issue by RoVi80** [sopra-fs23-group-08/server#14]
Story : As a player in-game I want to see other players current score, round-position, and their current status in the betting round (folded, called etc.) to inform my decision making. 

Acceptance criteria: 

- [x] sopra-fs23-group-08/server#38
- [x] sopra-fs23-group-08/client#21
- [x] sopra-fs23-group-08/client#20
- [x] sopra-fs23-group-08/client#19

Priority: Critical 
Estimate: 8 h

**Comment by S3r4f1n** [comment]
closed in: e32ab71c34bca3726e2500695f0847d857ed126d
